angular.module('capFinPlanning.templates', []).run(['$templateCache', function($templateCache) {
  "use strict";
  $templateCache.put("views/footer.tmpl.html",
    "");
  $templateCache.put("views/header.tmpl.html",
    "");
  $templateCache.put("views/home.html",
    "<div class=container><div class=row><div class=\"jumbotron clearfix\"><div class=col-sm-3><img src=\"./app/images/bill.jpg\"><br><div style=font-size:24px><strong>Bill Christian</strong></div><div style=font-size:12px>Certified Financial Planner ™</div><br><br></div><div class=\"col-sm-9`\"><h1>Capital Financial Planning</h1><h3>Assisting Clients In the Accumlation and Preservation or Wealth</h3><p>We identify your goals and your dreams and then plan to achieve them, while building and preserving wealth.</p></div></div></div><div class=row><div class=\"col-md-8 col-md-offset-2\"><ul><li><strong>Are you ready for retirement? Is it important to you to have a guaranteed monthly income?</strong></li><li><strong>Do you need a comprehensive financial plan for tax, estate, investment, retirement and education issues?</strong></li><li><strong>Do you need a second opinion about the proper allocation of your investments? Are you worried about your 401(k)?</strong></li><li><strong>Is your estate plan up to date?</strong></li><li><strong>Is your life insurance adequate?</strong></li></ul></div></div></div>");
  $templateCache.put("views/resume.html",
    "<div class=container><div class=row><div class=\"col-md-6 col-md-offset-3\"><h2>Background</h2><p>Founded Capital Financial Planning Group in 1996 after a lengthy career as corporate legal counsel.</p><h2>Focus</h2><p>Planning and investing for retirement is our main focus. Building and protecting your nest egg is achieved always by diversification and by selecting only the best and most experienced companies for: individual stocks, mutual funds, REIT’s (real estate), annuities, insurance, energy or other investments.</p><h2>Designations</h2>J.D., CFP<h2>Teaching</h2><ul><li>Adjunct Professor, Financial Planning</li><li>University of Houston 2006-2008</li></ul><h2>Honors</h2><ul><li><a href=\"http://www.fivestarprofessional.com/find-a-professional?market_id=25&prof_id=2&professional_name=Search+for+professional+name&company_name=capital+financial+planning\" target=_blank>Five-Star Wealth Manager</a>, Texas Monthly, Septembers 2009-2015</li></ul><h2>Licenses</h2>Securities: Series 7, 63, 79 Insurance & Annuities: TX, FL, IL<h2>Memberships</h2>Financial Planning Association (FPA) Houston FPA Chapter State Bar of Texas<h2>Education</h2>The University of North Carolina (Chapel Hill), B.A. English The University of Virginia Law School, J.D. Tulane School of Law, L.L.B.</div></div></div>");
  $templateCache.put("views/root.html",
    "<nav class=\"navbar navbar-default\"><div class=container><div class=row><div class=navbar-header><button type=button class=\"navbar-toggle collapsed\" data-toggle=collapse data-target=#bs-example-navbar-collapse-1 aria-expanded=false><span class=sr-only>Toggle navigation</span> <span class=icon-bar></span> <span class=icon-bar></span> <span class=icon-bar></span></button> <a class=navbar-brand href=#>{{brand}}</a></div><div class=\"collapse navbar-collapse\" id=bs-example-navbar-collapse-1><ul class=\"nav navbar-nav\"><li><a ui-sref=capFinPlanning.resume>Company Profile</a></li><li uib-dropdown on-toggle=toggled(open)><a href id=simple-dropdown uib-dropdown-toggle>Services</a><ul class=dropdown-menu uib-dropdown-menu aria-labelledby=simple-dropdown><li ng-repeat=\"choice in items\"><a href=# ui-sref={{choice.uisref}}>{{choice.name}}</a></li></ul></li></ul></div></div></div></nav><div ui-view></div><hr><div class=container><div class=row><p style=\"text-align: center\">William G. Christian, J.D., CFP</p><p style=\"text-align: center\">975 Corbindale, Suite 109, Houston TX 77024</p><p style=\"text-align: center\"><strong>Tel: 713-932-1955</strong> | Fax: 713-932-9132</p><p style=\"text-align: center\"><strong><a href=\"mailto:bill@capitalfinancialplanning.com?cc=billchristian@ims-securities.com\">Email:</a></strong> billchristian@ims-securities.com</p><p style=\"font-size: 10px;text-align: center\">ONLY TEXAS RESIDENTS ARE AUTHORIZED TO USE THESE SERVICES</p><div class=\"col-md-6 col-md-offset-3\"><p style=\"font-size: 6px\">William Christian is a Registered Representative of IMS Securities, Inc.(IMS), Member <a href=\"http://www.finra.org/\" target=_blank>FINRA</a>/<a href=\"http://www.sipc.org/\" target=_blank>SIPC</a> and an Investment Advisor Representative of IMS Financial Advisors, Inc.(IMSFA), a Registered Investment Advisor located 10205 Westheimer Rd., Suite 500, Houston, TX 77042 (713) 266-2993. All information herein has been prepared solely for informational purposes, and is not an offer to buy or sell, or a solicitation of an offer to buy or sell any security or instrument or to participate in any particular trading strategy. William Christian, Capital Financial Planning Group, IMS, and IMSFA do not make any representations or warranties as to the accuracy, timeliness, suitability, completeness, or relevance of any information prepared by any unaffiliated third party, whether linked to this web site or incorporated herein, and take no responsibility. All such information is provided solely for convenience purposes only. William Christian, Capital Financial Planning Group, IMS, and IMSFA do not endorse, control, or receive compensation from any of the third party advertisers within this website. William Christian, Capital Financial Planning Group, IMS, and IMSFA are not affiliated with any of the firms or entities listed unless specifically stated.</p></div></div></div>");
  $templateCache.put("views/services-comprehensive.html",
    "<div class=container><div class=row><div class=\"col-xs-8 col-xs-offset-2\"><h2>Comprehensive Financial Plan</h2><p>One of the ways to build a roadmap to financial freedom is through a comprehensive financial plan. We can provide such a plan which will assist you in achieving your financial goals and objectives. The components of a comprehensive plan include not only the retirement planning, estate planning, and investment planning described in other parts of this website but also educational planning for the funding of college education or other educational goals and tax planning to suggest tax advantages you might otherwise overlook. With a financial roadmap you will be more confident about how to find financial freedom.</p><h2>Modular Plan</h2><p>You may wish to concentrate on just one component of a financial plan, for example: \"retirement\", in which case a modular plan could be prepared for you to address that specific concern.</p></div></div></div>");
  $templateCache.put("views/services-retirement.html",
    "<div class=container><div class=row><div class=\"col-xs-8 col-xs-offset-2\"><h2>Retirement Planning</h2><p>One of the most difficult decisions that people face is deciding what to do in retirement and when to make that transition.</p><p>Where do you want to be and what do you want to be doing in the golden years?</p><p>With our counseling you can achieve the financial security you seek and realize your dreams.</p><h2>Annuities</h2><p>Many companies today offer annuities with guaranteed income for life and it's our job to determine what would be tailored to your situation and show you a range of appropriate choices that are in your best interests.</p></div></div></div>");
}]);
